#basic_network_setup.yaml
---
- name: basic_network_setup
  hosts: Routers
  gather_facts: no

  tasks:
    - name: Change hostname
      template:
        src: templates/hostname.j2
        dest: /tmp/hostname.cfg
    - ios_config:
        src: /tmp/hostname.cfg

    - name: Set local password
      template:
        src: templates/local_password.j2
        dest: /tmp/local_password.cfg
      vars:
        enable_password: "telecomS144"
        username: "chance"
        user_password: "telecomS144"
    - ios_config:
        src: /tmp/local_password.cfg

    - name: Configure SSH and disable Telnet
      template:
        src: templates/ssh_config.j2
        dest: /tmp/ssh_config.cfg
    - ios_config:
        src: /tmp/ssh_config.cfg

    - name: Limit console and VTY access
      template:
        src: templates/access_limit.j2
        dest: /tmp/access_limit.cfg
    - ios_config:
        src: /tmp/access_limit.cfg

    - name: Configure logging and timestamps
      template:
        src: templates/logging_config.j2
        dest: /tmp/logging_config.cfg
    - ios_config:
        src: /tmp/logging_config.cfg

    - name: Configure R1
      template:
        src: templates/interface_config.j2
        dest: /tmp/interface_config.cfg
      vars:
        interface: "G0/0"
        ip_address: "100.64.1.1"
        subnet_mask: "255.255.255.252"
    - ios_config:
        src: /tmp/interface_config.cfg
      when: inventory_hostname == 'R1'

    - name: Configure R2 Interface
      template:
        src: templates/interface_config.j2
        dest: /tmp/interface_config.cfg
      vars:
        interface: "G0/0"
        ip_address: "100.64.1.2"
        subnet_mask: "255.255.255.252"
    - ios_config:
        src: /tmp/interface_config.cfg
      when: inventory_hostname == 'R2'

    - name: Configure R2 Interface
      template:
        src: templates/interface_config.j2
        dest: /tmp/interface_config.cfg
      vars:
        interface: "G1/0"
        ip_address: "100.64.2.1"
        subnet_mask: "255.255.255.252"
    - ios_config:
        src: /tmp/interface_config.cfg
      when: inventory_hostname == 'R2'

    - name: Configure R2 VLAN
      template:
        src: templates/vlan_config.j2
        dest: /tmp/vlan_config.cfg
      vars:
        interface: "G0/0.10"
        vlan_id: "10"
        ip_address: "192.168.10.2"
        subnet_mask: "255.255.255.0"
    - ios_config:
        src: /tmp/vlan_config.cfg
      when: inventory_hostname == 'R2'

    - name: Configure R2 VLAN
      template:
        src: templates/vlan_config.j2
        dest: /tmp/vlan_config.cfg
      vars:
        interface: "G0/0.20"
        vlan_id: "20"
        ip_address: "192.168.20.1"
        subnet_mask: "255.255.255.0"
    - ios_config:
        src: /tmp/vlan_config.cfg
      when: inventory_hostname == 'R2'

    - name: Configure R3
      template:
        src: templates/interface_config.j2
        dest: /tmp/interface_config.cfg
      vars:
        interface: "G1/0"
        ip_address: "100.64.2.2"
        subnet_mask: "255.255.255.252"
    - ios_config:
        src: /tmp/interface_config.cfg
      when: inventory_hostname == 'R3'

    - name: Writing to memory
      template:
        src: templates/write_memory.j2
        dest: /tmp/write_memory.cfg
    - ios_config:
        src: /tmp/write_memory.cfg
