name: Ansible Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run Ansible Playbook
      run: ansible-playbook --vault-password-file vault_password.txt -i inventory.ini run_network_config.yaml
